FROM golang:1.20.3-alpine as builder

COPY ChatGPT-to-API /root/ChatGPT-to-API
COPY Authenticatior /root/Authenticatior



{}
{}

WORKDIR /root/ChatGPT-to-API
RUN go build && \
    chmod -R +x /root/ChatGPT-to-API
WORKDIR /root/Authenticatior
RUN go build && \
    chmod -R +x /root/Authenticatior

FROM python:3.9-slim
LABEL Name=chatgpttoapi Version=0.0.1

WORKDIR /app

COPY --from=builder /root/ChatGPT-to-API/freechatgpt /app/freechatgpt
COPY --from=builder /root/Authenticatior/authentication /app/authentication
COPY requirements.txt /app/requirements.txt

RUN pip3 install -r requirements.txt

EXPOSE 8080

CMD ["python3", "run.py"]
