version: '3.4'

services:
  chatgpttoapi:
    image: chatgpttoapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080/tcp
      - 8080:8080/udp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./run.py:/app/run.py
      - ./cache:/app/cache
      - ./log:/app/log
      - ./certifications:/app/certifications
    tty: true
    stdin_open: true
    container_name: chatgpttoapi
    restart: unless-stopped
